### PR TITLE
Add shop project boilerplate

### PR DESCRIPTION
**Pull request by mbovel**
This PR adds boilerplate for the shop project that the participants can use. Specifically, it setups static files, so that the front-end is served at `/` and can call Django back-end at `/shop`.

There is one problem left, when I try to add a `Product` model (not included in this PR) and the associated admin view, I always get this error:

image

Any idea why? Seems like my `Product` model is not taken into account when migrating. Is something mis-configured? Should my model be imported/declared somewhere else?

### CODE REVIEW

**Comment by mbovel** [comment]
Tried this: https://stackoverflow.com/a/36453000, but does not solve the problem.

**Comment by msom** [comment]
Did you add the app to INSTALLED_APPS (and then run makemigrations & migrate)?

**Comment by msom** [comment]
Also, I think you need to import your model somewhere else (e.g. in the admin.py or views.py) or it might not get autodetected...

**Comment by mbovel** [comment]
> Did you add the app to INSTALLED_APPS (and then run makemigrations & migrate)?

Yes, in `webservice/settings.py`: 

```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'shop'
]
```

> Also, I think you need to import your model somewhere else (e.g. in the admin.py or views.py) or it might not get autodetected...

I use it in `shop/admin.py`:

```python
from shop.models import Product

@register(Product)
class ProductAdmin(ModelAdmin):
    pass
```

**Comment by mbovel** [comment]
I solved the problem by explicitly running `env/bin/python manage.py makemigrations shop` instead of just `env/bin/python manage.py makemigrations`.

Is that generally needed? Or is that a sign that something is still mis-configured here?

**Comment by msom** [comment]
I didn't need to call that explicitly anytime, I guess it could be just a messed up situations with the DB at time of makemigrations?

**Comment by mbovel** [comment]
The following comment under [this answer](https://stackoverflow.com/a/36154224) explains the problem I had:

Screenshot 2021-06-24 at 12 06 05

My mistake was to not commit `migrations/__init__.py`. Now everything works as expected 😄

**Review by msom — APPROVED** [review]

**Pull request merged**
